twilson63/permaweb-cookbook

- docs/src/concepts/arns.md
Just tweaking some of the whitespace so it renders better in the markdown renderer 🖖
> docs: ✍️ formatting whitespace on example JSON

- docs/src/concepts/README.md
- docs/src/guides/README.md
Updated Readme(s) for Core Concepts and Guides to include block about creating issues and contributing.
> feat(core concept and guides): update READMEs to include description #33

- docs/src/concepts/postTransaction.md
Editing the Post Transacrtions Core Concept snack for clarity and consistency
> docs: editing post-transaction for clarity

- docs/src/concepts/smartweave.md
The writing in the "Why is SmartWeave important?" section repeated `you need`  as part of its explanations a few times.
This isn't quite the neutral descriptive voice we're shooting for.  Something short of academic but still a little objective is ideal. These edits state the reasons for SmartWeave with a more impersonal tone, removing explicit references to the reader.
> docs: edits for smartweave snack

- docs/src/.vuepress/config.js
> chore: update site index

- README.md
- docs/deploy.mjs
- docs/package.json
- docs/src/concepts/README.md
- docs/yarn.lock
Please code review ./docs/deploy.mjs 
The script requires a wallet.json to run, so you will not be able to verify the code works, I am happy to do a screen share to get signoff as well.
> Twilson63/chore deploy #39

- docs/src/concepts/arns.md
> chore: enable json syntax highlighting

- docs/src/.vuepress/config.js
- docs/src/guides/deployment/arkb.md
- docs/src/guides/deployment/bundlr-cli.md
add basic guides for bundlr and arkb cli
> add basic guides for bundlr and arkb cli

- docs/src/.vuepress/config.js
- docs/src/guides/README.md
for code blocks 
I also disabled line numbers in the config.ts file.
> chore(guides readme #46): added toc to guides readme

- docs/src/.vuepress/config.js
- docs/src/guides/README.md
- docs/src/guides/deployment/github-action.md
Took a first take of a guide for a github action, based on the work I just did with the cookbook for the github action.
> feat(github-action): #25 added guide for github action

- docs/src/guides/deployment/bundlr-cli.md
> change arkb to bundlr

- docs/src/.vuepress/config.js
- docs/src/guides/querying-arweave/queryingArweave.md
> docs: update the navigation index of the Guides section to be collapsed.

- docs/src/.vuepress/config.js
- docs/src/guides/smartweave/warp/readstate.md
#67 Warp SDK Guide to read contract state
> guide(warp): Readstate guide for warp SDK #67

- docs/src/.vuepress/config.js
- docs/src/guides/smartweave/warp/deploying-contracts.md
- docs/src/guides/smartweave/warp/evolve.md
- docs/src/guides/smartweave/warp/readstate.md
A Sub Guide to warp SDK on how to evolve SmartWeave Contracts using the Warp SDK
> guides(warpSDK): #79 Evolve SmartWeave Contracts

- docs/src/guides/deployment/arkb.md
- docs/src/guides/deployment/bundlr-cli.md
- docs/src/guides/posting-transactions/arweave-js.md
- docs/src/guides/posting-transactions/bundlr.md
- docs/src/guides/querying-arweave/ar-gql.md
> chore: collapse install guides for NPM / YARN

- docs/package.json
- docs/src/.vuepress/config.js
- docs/src/.vuepress/styles/index.scss
- docs/src/.vuepress/styles/index.styl
Fixing the container plugin integration 😅
> fix: repair the container plugin integration

- docs/src/.vuepress/config.js
- docs/src/concepts/README.md
- docs/src/concepts/permawebApplications.md
First draft of Core Concept for permaweb applications, please review and comment
> concept(permaweb): #98 added core concept document for the permaweb

- docs/src/.vuepress/config.js
- docs/src/kits/README.md
- docs/src/kits/react/create-react-app.md
- docs/src/kits/react/index.md
Create React App starter kit and repo
> Add Create React App starter kit

- docs/src/kits/react/create-react-app.md
made couple of updates in react-starter-kit and made it compatible for yarn package manager as well
> react-starter-kit has been updated

- docs/src/concepts/manifests.md
isn't everything better with cat photos?
> docs: path-manifests are better with cat photos

- docs/src/kits/react/index.md
- docs/src/kits/react/vite.md
Add a Vite example of creating permaweb apps with React. I believe this is a better alternative to CRA.
> kit(React): #138 Add Vite permaweb app example

- docs/src/concepts/permaweb.md
Just bringing the diagrams in line with some of the others on the cookbook 😎
> docs: update the diagrams on the permaweb

- docs/src/.vuepress/config.js
- docs/src/getting-started/quick-starts/hw-cli.md
- docs/src/getting-started/welcome.md
> getting-started(hello-world-cli): #130 create hello world cli

- docs/src/kits/svelte/index.md
- docs/src/kits/svelte/vite.md
This kit is for you @DanMacDonald
> kit(svelte/vite): Create a Svelte/Vite Permaweb App #146

- docs/src/guides/README.md
- docs/src/guides/http-api.md
> add tip for api guide. add links to snacks

- docs/src/.vuepress/public/background.svg
- docs/src/.vuepress/styles/index.scss
- docs/src/index.md
Dark mode comes to the cookbook!
> landing(dark): added better dark mode #158

- docs/src/index.md
Change Welcome button to Read Now button
> update(landing): #162 change welcome to read now

- docs/src/kits/react/create-react-app.md
Small edits to the react starter kit
> verbage fixes for react guide

- docs/src/.vuepress/config.js
- docs/src/concepts/bundles.md
Learnt a lot putting this together, welcome to any feedback! 😄
> CoreConcepts: Bundles and Bundling

- docs/src/.vuepress/config.js
Adding Tracker for Site Analytics
> chore(config): added tracker for analytics

- docs/src/.vuepress/config.js
- docs/src/concepts/keyfiles-and-wallets.md
May need a review from @twilson63 @DanMacDonald or anyone else who is good with cryptography to check this :D
I've tried to keep it relatively short and sweet so open to any feedback if you think it's missing anything too.
> CoreConcepts: Keyfiles and Wallets

- docs/src/.vuepress/config.js
- docs/src/concepts/gateways.md
Hey guys, if you have any feedback or adjustments I should make, or anything I should add just let me know 🙂 thanks!
> CoreConcepts: Gateways

- docs/src/concepts/arns.md
- docs/src/concepts/smartweave.md
> hide todo comments

- docs/src/.vuepress/config.js
- docs/src/guides/README.md
> Guides section readment update

- docs/src/concepts/keyfiles-and-wallets.md
Hey @felwintrr did a pass on the wallets doc to add a little more detail I wish I had when I was starting 😎
> docs: update the key-files and wallets doc

- docs/src/.vuepress/layouts/Layout.vue
Inserting two missing blanks in lavout.vue
> Correcting two typos in layout.vue

- docs/src/.vuepress/config.js
- docs/src/concepts/bundlers.md
> Organize the core-concepts articles in the order that optimizes learning progress

- docs/src/concepts/README.md
- docs/src/concepts/bundlers.md
- docs/src/concepts/keyfiles-and-wallets.md
- docs/src/concepts/queryTransactions.md
- docs/src/concepts/tags.md
- docs/src/guides/posting-transactions/dispatch.md
> chore: make the core-concepts landing page match the index

- docs/src/.vuepress/config.js
- docs/src/concepts/README.md
Now with less repetition of the word "Transaction" making it easier to read and navigate.
> chore: remove repeated words from index

- docs/src/.vuepress/config.js
- docs/src/guides/README.md
- docs/src/guides/querying-arweave/queryingArweave.md
- docs/src/guides/querying-arweave/search-gateway.md
- docs/src/guides/querying-arweave/search-indexing-service.md
Hey! Added some documentation for the `arweave-search.goldsky.com` endpoint. Would love your feedback!
> docs: document goldsky's Search endpoint

- docs/src/concepts/bundlers.md
- docs/src/concepts/bundles.md
Tested locally, lets try in production 😎
> chore: fix the links for the root navigation elements

- docs/src/.vuepress/config.js
- docs/src/concepts/bundlers.md
- docs/src/concepts/bundles.md
Apparently THIS is the correct commit.
Also includes some re-phrasing of the language around L1/L2, apparently my branches and PR's got crossed.
> chore: fix navigate index links

- docs/src/getting-started/quick-starts/hw-code.md
fix Upload using bundlr  Command
> fix:  error command

- docs/src/es/getting-started/quick-starts/hw-code.md
The English command has been modified, modify the es language
> fix: error command  es

- docs/src/.vuepress/components/Topbar.vue
> Change top bar to hackathon notice

- docs/src/.vuepress/sidebar.js
- docs/src/getting-started/quick-starts/hw-no-code.md
Added no-code example to cookbook
> enabled no-code guide with simple no-code app

- docs/src/guides/querying-arweave/queryingArweave.md
- docs/src/guides/querying-arweave/search-indexing-service.md
- docs/src/zh/concepts/gateways.md
- docs/src/zh/guides/querying-arweave/search-indexing-service.md
> fix: markdown markdown syntax error

- docs/src/getting-started/quick-starts/hw-cli.md
Fixed a couple of typos on the guide
> Update Hello World CLI Guide

- docs/src/kits/react/vite.md
Fixed some typos with the react guide, also added some details about funding an irys account
> Fix some typos with the react app

- docs/src/kits/react/vite.md
This guide is missing a step with the vite config setting.
> Add the vite.config update

- docs/src/getting-started/quick-starts/hw-code.md
Fixed a typo on hello world code guide
> fix: typo on hello world code

- docs/src/guides/posting-transactions/README.md
- docs/src/guides/posting-transactions/turbo.md
Adds a guide for uploading a file or data item with `turbo` sdk.
> feat: posting transactions turbo

- docs/src/.vuepress/sidebar.js
- docs/src/guides/posting-transactions/irys.md
- docs/src/guides/posting-transactions/turbo.md
Small update to guide for uploading with Turbo, includes adding tags to files during upload. Also added the page to sidebar.
> Docs(Turbo): Update to guide for uploading with Turbo

- docs/package.json
- docs/src/.vuepress/config.js
- docs/yarn.lock
installed plugin that makes all code blocks have a simple "copy" button
> feat: Installed code copy plugin

- docs/src/getting-started/quick-starts/hw-code.md
updated the install command, added an info box, and corrected a typo.
> fix: updated install command

- docs/src/.vuepress/components/Navbar.vue
- docs/src/.vuepress/components/Onboarding.vue
- docs/src/.vuepress/sidebar.js
- docs/src/.vuepress/styles/index.scss
- docs/src/es/index.md
Have to explicitly point the links to the .html file so that opening in new tab works. Currently vuepress redirects the link to the correct .html path when clicking on them.
> fix: not found error when opening in new tab

- docs/src/concepts/arfs/data-model.md
Closes #325 
Removes repeated list items
> chore(cookbook): remove repeated lines in arfs

- docs/src/guides/posting-transactions/turbo.md
This PR uses the Quick Start code from the ArDrive Turbo GitHub repository, with up-to-date code for uploading data to Arweave with Turbo.
> Update Turbo guide for posting transactions

- .vite/deps_temp_801fad7e/package.json
- docs/src/.vuepress/layouts/Layout.vue
The <Topbar /> component has been commented out in the main layout to temporarily remove it from the UI
> Comment out Topbar in Layout.vue

- docs/src/concepts/vouch.md
As VouchDAO is built on SmartWeave/Warp and hasn't been updated for a few years, I think it makes sense to remove references to VouchDAO in particular. 
However as ANS-109 is part of the Arweave protocol we can leave the general information here in case users are interested in building with it etc.
> Update Vouch Core Concept

- src/getting-started/quick-starts/hw-cli.md
- src/getting-started/quick-starts/hw-code.md
- src/getting-started/welcome.md
This PR updates the use of the term "permaweb" to "Permaweb" for consistency.
> Getting Started consistency
