- docs/src/guides/posting-transactions/arweave-js.md
- docs/src/guides/posting-transactions/bundlr.md
- docs/src/guides/posting-transactions/dispatch.md
Removing line numbers from code blocks as it results in less visual noise. I recommend only using line numbers when it's important to reference a specific line in the code from the accompanying written description.
> chore: remove line numbers for example node where they are not needed

- docs/src/.vuepress/config.js
- docs/src/guides/README.md
- docs/src/guides/dns-integration/server-side.md
Added Server Side Guide using Deno Deploy
I mainly wanted to add this guide to test the controller feature of ArNS, I have modified the cookbook ANT contract to use the COOKBOOK wallet as the controller, so now my automated deploy should work when this PR is merged to main.
> feat(dns): #52 added server-side dns guide

- docs/src/concepts/postTransaction.md
Miner tweaks,  it's important to surface dropped transactions but not scare off any new developer just learning about arweave.
> docs: rephrase the dropped transactions description

- docs/src/concepts/postTransaction.md
After reflecting on it, as tempting as it is to borrow `Layer 1` and `Layer 2`  from the Ethereum ecosystem, I've realized it's not the bet analogy.
'Layer 2' scaling solutions on Ethereum don't really scale, they relieve some pressure on the underlying Ethereum network while at the same time experiencing their own scaling challenges.  At some point there's a real chance that this becomes a top issue for Ethereum and the narrative switches to saying "Layer 2 Doesn't scale".  In this scenario it's better to differentiate services built on top of Arweave from "Layer 2 scaling solutions". 
"Permaweb Services" built on top of Arweave afford a variety of different utilities, Indexing, caching, bundling, sequencing etc. I've updated the "Posting Transactions" Core Concept to remove references …
> docs: remove layer 1, layer 2 references from CoreConcept

- docs/src/.vuepress/config.js
- docs/src/concepts/README.md
- docs/src/concepts/post-transactions.md
- docs/src/guides/posting-transactions/arweave-js.md
- docs/src/guides/posting-transactions/bundlr.md
- docs/src/guides/posting-transactions/dispatch.md
Making the individual guides for posting transactions also available under the `Posting Transactions` snack in the `Core Concepts` for better locality of reference / discoverability.
> chore: update organization of posting transactions index

- docs/src/concepts/post-transactions.md
- docs/src/guides/posting-transactions/arweave-js.md
lets make the CoreConcept page a little more welcoming.
> docs: move scary wording to the arweave-js guide

- docs/src/.vuepress/config.js
- docs/src/guides/README.md
- docs/src/guides/posting-transactions/README.md
Currently when you expand one of the Post Transactions examples, it expands the cookbook index in two places which is confusing. To maintain a good locality of reference for new devs, the examples are located in close proximity to the "Posting Transactions" core concept. 
This PR makes that be their primary location and posts a link to them from the Guides section so they only expand the index in one place.
> docs: reorganizing the index for posting transactions examples

- docs/src/concepts/permawebApplications.md
- docs/src/concepts/post-transactions.md
The links leading to the react and svetle starter kits from the permaweb applications page are broken. This PR fixes them.
> fix react and svetle links in the permawebApplications

- docs/src/.vuepress/styles/index.scss
Improve the legibility of tables in the documentation.
Old:
New:
> Update table background colors

- docs/src/.vuepress/config.js
- docs/src/guides/deployment/index.md
- docs/src/guides/dns-integration/index.md
- docs/src/guides/smartweave/index.md
- docs/src/guides/testing/index.md
Add landing pages for:
- Deploying Apps
- DNS Integration
- SmartWeave
- Testing
This creates a url route for these sections.
> Add missing landing pages for main topics

- docs/src/guides/posting-transactions/arweave-js.md
- docs/src/guides/posting-transactions/bundlr.md
- docs/src/guides/posting-transactions/dispatch.md
In multiple places, the file "postTransaction.md" was mistakenly referenced. All references to "postTransaction.md" have been updated to "post-transactions.md", which is the correct name of the file that was intended to be referred to.
> refactor: Update references from postTransaction.md to post-transactions.md

- docs/src/concepts/bundlers.md
- docs/src/concepts/bundles.md
Trying to differentiate bundling services from Ethereum L2s as there are a number of key areas where the analogy breaks down.
1. L2's on ethereum perform some kind of rollup where the state of the side chain is compressed and posted to Ethereum. Arweave bundles do no such thing, every single transaction in a bundle appears as part of the native blockchain, there is no compression at work.
2. L2's on ethereum don't really scale, they quickly run into blockspace and have to rely on a fee-market to compete for transaction inclusion. Arweave bundles are not so limited. Everyone who wants to be in a bundle can have their data included. They never bid in a fee market for transaction inclusion, they just pay the network storage cost and bundlers markup. Everyone pays the exact same fee.
> docs: remove references to L1 and L2 from bundle docs

- docs/src/getting-started/quick-starts/hw-nodejs.md
Updated the bundlr import from:
```js
const bundlr = new Bundlr.default(
"http://node2.bundlr.network",
"arweave",
jwk
);
```
to:
```js
const bundlr = new Bundlr(
"http://node2.bundlr.network",
"arweave",
jwk
);
```
> docs: bundlr no longer needs .default()

- docs/src/.vuepress/config.js
Before:
```
https://cookbook.arweave.dev/concepts/
```
After: 
```
https://cookbook.arweave.dev/concepts/index.html
```
> fix: disable slash redirect at build time.

- docs/src/guides/deployment/github-action.md
This PR fixed the Github Action example, properly passing the parameters to the Irys SDK, now that it [accepts a single object parameter](https://docs.irys.xyz/developer-docs/irys-sdk/migration-guide#constructor)
> docs(github-action): fix example code to properly pass parameters to Irys SDK

- docs/src/references/README.md
Added the links to the subtopics for the references and the closing line of contributing to the GitHub repo of the cookbook.
Before -
> docs: fix references page

- docs/src/guides/querying-arweave/search-indexing-service.md
I think this was added accidentally to this page - it doesn't support the search API, at least with this endpoint: 
https://knn3-gateway.knn3.xyz/arseeding/graphql
None of the listed examples work in the endpoint here so it doesn't adhere with our loose 'Search Spec'. 
The reason this came up was that we had a few users email us about this, since the copy did say to ask Goldsky for support. 
```
query just_values {
transactions(
first: 10,
tags: [
{
values: ["cat"]
}
]
) 
{
edges {
node {
id
tags {
name
value
}
}
}
}
}
```
> Remove knn3 gateway as search indexer

- docs/src/.vuepress/sidebar.js
- docs/src/concepts/post-transactions.md
- docs/src/guides/README.md
- docs/src/guides/deploying-manifests/akord.md
- docs/src/guides/posting-transactions/README.md
- docs/src/guides/posting-transactions/akord.md
- docs/src/guides/smartweave/atomic-assets/akord.md
- docs/src/guides/smartweave/atomic-assets/index.md
- docs/src/kits/react/akord.md
- docs/src/kits/react/index.md
- add Akord examples to the following guides:
- posting transactions
- deploying manifests
- atomic assets
- add Akord + Vite starter kit
- add Akord to the sidebar & README
> Add Akord to the docs

- .github/workflows/deploy.yml
Migrate deployment to using permaweb-deploy
> feat: migrate deploy to permaweb-deploy

- docs/src/.vuepress/sidebar.js
- docs/src/concepts/manifests.md
- docs/src/guides/deploying-manifests/akord.md
- docs/src/guides/deploying-manifests/turbo.md
Manifests recently received an upgrade that allows them to support a "fallback" id, which resolvers will use in place of a requested path that cannot be found, effectively acting as a 404 page.
This pr updates references to manually created manifests to show the updated version and include the "fallback" attribute. It also adds a guide page for creating and deploying a manifest using the Turbo SDK.
> Docs(Manifests): Updated manifest references to v0.2.0, added Turbo guide

- docs/src/concepts/permawebApplications.md
- docs/src/concepts/tags.md
This PR:
- Rewrote intro section to better reflect how people are building applications now AO is in mainnet
- Updated services section to change from sequencers/smartweave to compute/ao
- Updated Gateway section and included AR.IO as the gateway network of choice
- Updated bundling section to use ArDrive Turbo instead of Irys
- Updated application development section to include AO and removed images referencing Irys Network
> Update Permaweb Applications

- docs/languages/strings/en.json
- docs/src/.vuepress/sidebar.js
- docs/src/references/glossary.md
- docs/src/references/llms.md
This PR adds two new reference pages to the permaweb cookbook documentation: a Permaweb Glossary and an LLMs.txt builder tool, both with proper light/dark mode theming integration.
- **`docs/src/references/glossary.md`** - Embedded Permaweb Glossary tool
- **`docs/src/references/llms.md`** - LLMs.txt Builder tool
- Both iframes use CSS classes for light/dark mode switching
- Color parameters match the project's CSS variables:
- Light mode: `--c-bg: #f2f2f2`, `--c-text: #242424`, `--c-brand: #ff5f15`
- Dark mode: `--c-bg: #1b1b1f`, `--c-text: #e0e0e0`
- Responsive design with proper iframe styling
- No header display on glossary for seamless integration
> Add Permaweb Glossary and LLMs.txt Reference Pages

- docs/src/community/README.md
As the Atomic Assets guides are currently referencing SmartWeave, I think it makes sense to remove the link so we aren't pointing users towards outdated content.
> Remove atomic assets link from community page
